# Site settings
title: Matt Cole
email: matt@matt-cole.co.uk
description: >
  Just another "just another dev blog" blog
baseurl: ''
url: 'http://blog.matt-cole.co.uk'
# twitter_username: jekyllrb
github_username:  mattwcole

# Build settings
markdown: kramdown
# highlighter: rogue
